### ISSUE TITLE
Compatibility with Webtrees 1.7.1

### ISSUE THREAD

**Issue by DJAlik** [mnoorenberghe/webtrees-facebook#20]
Doesn't appear to be working with the latest webtrees. I am getting a blank page when trying to open my site since the upgrade.

**Comment by DJAlik** [comment]
Deleting the module allowed me to open the site so the issue is definitely with this module

**Comment by trindal** [comment]
Matt,
do you have any plans to make the webtrees-facebook module compatible with wt 1.7.0+?
There is a small community out here using your excellent module and would like to know whether this module will be modified or if we need to discontinue the use of it if upgrade to 1.7.0/1 is required for other reasons.
Regards,
T

**Comment by mnoorenberghe** [comment]
I will when I have time since I'm a user myself but I haven't had time yet. If someone else has a fix in the meantime I can review/merge it.

**Comment by Chetn** [comment]
Hi Matt,
I am havin some issues with facebook login on  webtrees1.6.2
Face book says "Submit for Login Review
Some of the permissions below have not been approved for use by Facebook."
This can be avoided (automatic approval by facebook) if there are only 3 login permissions email, public_profile, user_friends are asked for.
I tried to modify module.php to this.
const scope = 'public_profile,user_friends,email';
Facebook approves the app, but when a user tries to login I get this message
"You must grant access to your email address via Facebook in order to use this website. Please uninstall the application on Facebook and try again."
I am not a software guy and blindly hacking.
Any help to resolve this issue would be very welcome.

**Comment by mallamace** [comment]
I'm using 1.7.2 - I tried installing with no luck. WT has removed a downloadable file and replace with empty file. I would love to see new life with this plugin.

**Comment by mnoorenberghe** [comment]
This should be fixed by #23 which adds 1.7.9 support
